Update setup to central v11 config in new release, add pnet tau probs.
cms-hh-bbtautau/Framework pull request #16
Opened 2022-12-20 18:14 UTC by riga

This PR updates the setup to

- use the `12_6_0_patch1` release containing the official v11 config published today, and
- includes the particle net outputs for tau probabilities.

The latter is a blunt copy of https://github.com/cms-tau-pog/NanoProd/pull/10 with one minor change: it uses the `cmssw_126x` branch of the https://gitlab.cern.ch/rgerosa/particlenetstudiesrun2 project, rather than `cmssw_124x` which Raffaele deleted today. It appears that he is still actively working on the `cmssw_126x` branch 😀, but things already run nicely.

2022-12-21 08:55 UTC, riga commented
@kandrosov 

I added two updates:

1. I enabled the PNet taggers for AK8 jets which required adding the proper model files through additional data repositories in `env.sh`. This was rather straight forward.

2. The issue related to crab jobs is somewhat more involved. The way the `scram build` and `scram build python` commands function changed recently. Before, they were creating symlinks / copies of all files found in `src/*/*/python` directories directly into the central `CMSSW_X_Y_Z/python` directory of the local checkout. This was picked up by crab's `sendPythonFolder` when building the job input archive, and everything worked fine. Apparently, `scram build [python]` does not do this any more (or not at the moment?). Instead, it create's init files that would directly point to the `src/*/*/python` folders, hence no symlinks are created and crab's bundling misses those files. Within the `src/*/*/` folders it only bundles `interface` and `data`. I was not aware of that change and it seems odd to me. The issue did not appear in the repo (and likely neither in the TAU POGs NanoProd) since only with this PR (and the above linked PR) an additional package is included (`git cms-addpkg RecoBTag/Combined`) whose python files will be missing in input job sandboxes. The other packages are shadowed from cvmfs as always.

So as a workaround, I added back manual symlinking of all python directories within the `env.sh` setup which does exactly what `scram build [python]` used to do, and indeed the crab jobs run smoothly.

2022-12-21 12:11 UTC, kandrosov requested changes

2022-12-21 12:11 UTC, kandrosov commented on NanoProd/customiseNano.py
> +    process.schedule = cms.Schedule(process.edPath,process.nanoAOD_step,process.endjob_step,process.NANOAODSIMoutput_step)
would it be possible to insert `edPath` without redefining the whole schedule? Something like
```
process.schedule.insert(0, edPath)
```

2022-12-21 12:11 UTC, kandrosov commented on NanoProd/customiseNano.py
> +    process.slimmedJetsUpdatedPNET.userData.userInts.src += ['pileupJetIdUpdatedPNET:fullId'];
is new pu id stored in nano?

2023-06-27 15:21 UTC, kandrosov commented
@riga I am going to close this PR since for the newer productions we'll use CMSSW_13_0_X-based setups, where PNet is already available.

2023-06-27 15:21 UTC, closed without merging