created branch for sync
cms-hh-bbtautau/Framework pull request #30
Opened 2023-03-28 13:23 UTC by valeriadamante

2023-03-28 13:45 UTC, kandrosov requested changes
- update ele selection
- put tau_eta cut in the config
- fix MET

2023-04-12 11:46 UTC, kandrosov requested changes

2023-04-12 11:46 UTC, kandrosov commented on Common/AnalysisTools.h
> +        //std::cout << std::endl;
```suggestion
```

2023-04-12 11:46 UTC, kandrosov commented on Common/AnalysisTools.h
> +          //std::cout << " count " << cnt << std::endl;
```suggestion
```

2023-04-12 11:46 UTC, kandrosov commented on Common/BaselineRecoSelection.h
> +        //std::cout << std::endl;
```suggestion
```

2023-04-12 11:46 UTC, kandrosov commented on Common/BaselineSelection.py
> +    """) # && (Electron_mvaIso_WP90 || (Electron_mvaNoIso_WP90 && Electron_pfRelIso03_all < 0.5))
don't change any B0 selections!

2023-04-12 11:46 UTC, kandrosov commented on config/samples_Run2_2018.yaml
> +      VSmu: VLoose
should be `Tight` isn't it?

2023-04-13 16:33 UTC, valeriadamante commented on Common/AnalysisTools.h
> +        //std::cout << std::endl;
ok

2023-04-13 16:34 UTC, valeriadamante commented on Common/AnalysisTools.h
> +          //std::cout << " count " << cnt << std::endl;
ok

2023-04-13 16:34 UTC, valeriadamante commented on Common/BaselineRecoSelection.h
> +        //std::cout << std::endl;
ok

2023-04-13 16:35 UTC, valeriadamante commented on Common/BaselineSelection.py
> +    """) # && (Electron_mvaIso_WP90 || (Electron_mvaNoIso_WP90 && Electron_pfRelIso03_all < 0.5))
ok

2023-04-13 16:35 UTC, valeriadamante commented on config/samples_Run2_2018.yaml
> +      VSmu: VLoose
nmmh maybe yes. Changed

2023-04-13 16:36 UTC, valeriadamante commented on config/samples_Run2_2018.yaml
> +      VSmu: VLoose
In this case all WPs are equal:
```
    eTau:
      VSe: VVLoose
      VSmu: Tight
      VSjet: Medium
    muTau:
      VSe: VVLoose
      VSmu: Tight
      VSjet: Medium
    tauTau:
      VSe: VVLoose
      VSmu: Tight
      VSjet: Medium
      ```

2023-04-20 14:38 UTC, kandrosov approved these changes

2023-04-20 14:39 UTC, merged